import { NextRequest, NextResponse } from 'next/server';
import { authenticateRequest, verifyTenantAccess } from '@/lib/auth';
import { db } from '@/lib/db';
import { sanitizeInsuranceInput } from '@/lib/insurance-security';
import { auditLogger } from '@/lib/insurance-audit';
import { calculateRenewalDates, generatePremiumSchedules, calculateLapseRisk } from '@/lib/insurance-renewals';

// ─── GET ───

export async function GET(req: NextRequest, { params }: { params: Promise<{ tenantId: string }> }) {
  const { tenantId } = await params;
  const auth = authenticateRequest(req);
  if (!auth.success) {
    return NextResponse.json({ error: auth.error }, { status: auth.status || 401 });
  }
  const ownership = verifyTenantAccess(auth, tenantId);
  if (!ownership.success) {
    return NextResponse.json({ error: ownership.error }, { status: ownership.status || 403 });
  }

  try {
    const { searchParams } = new URL(req.url);
    const action = searchParams.get('action');

    // ── GET ?action=scan ──
    // Scans for policies expiring within 30 days that don't have a renewal task yet
    if (action === 'scan') {
      const now = new Date();
      const thirtyDaysMs = 30 * 24 * 60 * 60 * 1000;
      const windowEnd = new Date(now.getTime() + thirtyDaysMs);

      // Find active policies expiring within 30 days
      const expiringPolicies = await db.policy.findMany({
        where: {
          tenantId,
          isDeleted: false,
          status: 'active',
          endDate: {
            gt: now,
            lte: windowEnd,
          },
        },
        include: {
          renewalTasks: {
            where: { isDeleted: false },
          },
        },
      });

      // Filter out policies that already have a renewal task
      const policiesNeedingRenewal = expiringPolicies.filter(
        (p: any) => !p.renewalTasks || p.renewalTasks.length === 0
      );

      // Create RenewalTask records for each policy
      const createdTasks: any[] = [];
      for (const policy of policiesNeedingRenewal) {
        const endDate = new Date((policy as any).endDate);
        const dueDate = new Date(endDate.getTime() - 30 * 24 * 60 * 60 * 1000);

        const task = await db.renewalTask.create({
          data: {
            tenantId,
            policyId: policy.id,
            status: 'pending',
            dueDate,
            notes: `Auto-scanned renewal task for policy ${policy.policyNumber || policy.id}`,
          },
        });

        createdTasks.push(task);

        // Audit log for each created task
        auditLogger.log({
          tenantId,
          userId: auth.payload?.userId || auth.payload?.email || 'system',
          action: 'create',
          entityType: 'renewal_task',
          entityId: task.id,
          metadata: {
            policyId: policy.id,
            policyNumber: policy.policyNumber,
            autoGenerated: true,
            action: 'scan',
          },
        });
      }

      return NextResponse.json({
        scannedCount: expiringPolicies.length,
        alreadyTrackedCount: expiringPolicies.length - policiesNeedingRenewal.length,
        newTasksCreated: createdTasks.length,
        tasks: createdTasks,
      });
    }

    // ── GET ?action=bulk-status ──
    // Returns summary of renewal pipeline health
    if (action === 'bulk-status') {
      const now = new Date();
      const DAY_MS = 24 * 60 * 60 * 1000;

      // Helper to count expiring policies
      const countExpiring = async (days: number) => {
        const windowEnd = new Date(now.getTime() + days * DAY_MS);
        return db.policy.count({
          where: {
            tenantId,
            isDeleted: false,
            status: 'active',
            endDate: {
              gt: now,
              lte: windowEnd,
            },
          },
        });
      };

      const [expiring30, expiring60, expiring90] = await Promise.all([
        countExpiring(30),
        countExpiring(60),
        countExpiring(90),
      ]);

      // Count renewal tasks by status
      const allTasks = await db.renewalTask.findMany({
        where: { tenantId, isDeleted: false },
      });
      const tasksByStatus: Record<string, number> = {};
      for (const task of allTasks) {
        const s = (task as any).status || 'pending';
        tasksByStatus[s] = (tasksByStatus[s] || 0) + 1;
      }

      // Policies that will lapse (no renewal task + expiry < 30 days)
      const allExpiring30Policies = await db.policy.findMany({
        where: {
          tenantId,
          isDeleted: false,
          status: 'active',
          endDate: {
            gt: now,
            lte: new Date(now.getTime() + 30 * DAY_MS),
          },
        },
        include: {
          renewalTasks: {
            where: { isDeleted: false },
          },
        },
      });

      const policiesAtLapseRisk = allExpiring30Policies.filter(
        (p: any) => !p.renewalTasks || p.renewalTasks.length === 0
      );

      // Premium at risk
      const premiumAtRisk = policiesAtLapseRisk.reduce(
        (sum: number, p: any) => sum + parseFloat((p as any).premium?.toString() || '0'),
        0
      );

      return NextResponse.json({
        expiringIn30Days: expiring30,
        expiringIn60Days: expiring60,
        expiringIn90Days: expiring90,
        tasksByStatus,
        policiesAtLapseRisk: policiesAtLapseRisk.length,
        premiumAtRisk,
        lapseRiskPolicies: policiesAtLapseRisk.map((p: any) => ({
          id: p.id,
          policyNumber: p.policyNumber,
          insuredId: p.insuredId,
          premium: p.premium,
          endDate: p.endDate,
          riskScore: calculateLapseRisk(p, false),
        })),
      });
    }

    // ── GET ?action=generate-notices ──
    // (Also accessible via POST — documented below. GET falls through to a default message.)
    return NextResponse.json({
      error: 'Invalid action. Use scan, bulk-status, or see POST for generate-notices.',
    }, { status: 400 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// ─── POST ───

export async function POST(req: NextRequest, { params }: { params: Promise<{ tenantId: string }> }) {
  const { tenantId } = await params;
  const auth = authenticateRequest(req);
  if (!auth.success) {
    return NextResponse.json({ error: auth.error }, { status: auth.status || 401 });
  }
  const ownership = verifyTenantAccess(auth, tenantId);
  if (!ownership.success) {
    return NextResponse.json({ error: ownership.error }, { status: ownership.status || 403 });
  }

  try {
    const { searchParams } = new URL(req.url);
    const action = searchParams.get('action');

    // ── POST ?action=process ──
    // Processes renewal tasks in bulk
    if (action === 'process') {
      const body = await req.json();
      const { taskIds, action: processAction, notes } = body as {
        taskIds?: string[];
        action?: 'contact' | 'quote' | 'renew' | 'decline';
        notes?: string;
      };

      if (!taskIds || !Array.isArray(taskIds) || taskIds.length === 0) {
        return NextResponse.json({ error: 'taskIds array is required' }, { status: 400 });
      }
      if (!processAction || !['contact', 'quote', 'renew', 'decline'].includes(processAction)) {
        return NextResponse.json(
          { error: 'action must be one of: contact, quote, renew, decline' },
          { status: 400 }
        );
      }

      const processed: any[] = [];
      const errors: any[] = [];
      const sanitizedNotes = notes ? sanitizeInsuranceInput(notes) : undefined;

      for (const taskId of taskIds) {
        try {
          // Fetch the renewal task and its related policy
          const task = await db.renewalTask.findFirst({
            where: { id: taskId, tenantId, isDeleted: false },
            include: { policy: true },
          });

          if (!task) {
            errors.push({ taskId, error: 'Renewal task not found' });
            continue;
          }

          const policy = (task as any).policy;
          if (!policy) {
            errors.push({ taskId, error: 'Related policy not found' });
            continue;
          }

          if (processAction === 'contact') {
            await db.renewalTask.update({
              where: { id: taskId, tenantId },
              data: {
                status: 'contacted',
                notes: sanitizedNotes ? `${(task as any).notes || ''}\n[${new Date().toISOString()}] ${sanitizedNotes}` : (task as any).notes,
              },
            });

            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'renewal_task',
              entityId: taskId,
              changes: { status: { old: (task as any).status, new: 'contacted' } },
              metadata: { policyId: policy.id, policyNumber: policy.policyNumber },
            });

            processed.push({ taskId, action: 'contact', status: 'contacted', policyId: policy.id });
          }

          else if (processAction === 'quote') {
            await db.renewalTask.update({
              where: { id: taskId, tenantId },
              data: {
                status: 'quoted',
                notes: sanitizedNotes ? `${(task as any).notes || ''}\n[${new Date().toISOString()}] ${sanitizedNotes}` : (task as any).notes,
              },
            });

            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'renewal_task',
              entityId: taskId,
              changes: { status: { old: (task as any).status, new: 'quoted' } },
              metadata: { policyId: policy.id, policyNumber: policy.policyNumber },
            });

            processed.push({ taskId, action: 'quote', status: 'quoted', policyId: policy.id });
          }

          else if (processAction === 'decline') {
            // Mark renewal task as cancelled and old policy as lapsed
            await db.renewalTask.update({
              where: { id: taskId, tenantId },
              data: {
                status: 'cancelled',
                completedDate: new Date(),
                notes: sanitizedNotes ? `${(task as any).notes || ''}\n[${new Date().toISOString()}] DECLINED: ${sanitizedNotes}` : `${(task as any).notes || ''}\n[${new Date().toISOString()}] DECLINED`,
              },
            });

            await db.policy.update({
              where: { id: policy.id, tenantId },
              data: { status: 'lapsed' },
            });

            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'renewal_task',
              entityId: taskId,
              changes: { status: { old: (task as any).status, new: 'cancelled' } },
              metadata: { policyId: policy.id, policyNumber: policy.policyNumber, reason: 'declined' },
            });

            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'policy',
              entityId: policy.id,
              changes: { status: { old: policy.status, new: 'lapsed' } },
              metadata: { policyNumber: policy.policyNumber, reason: 'renewal_declined' },
            });

            processed.push({ taskId, action: 'decline', status: 'cancelled', policyId: policy.id, policyStatus: 'lapsed' });
          }

          else if (processAction === 'renew') {
            // ── Full Renewal Logic ──

            // Fetch the related product to get termsMonths
            const product = policy.productId
              ? await db.insuranceProduct.findFirst({
                  where: { id: policy.productId, tenantId, isDeleted: false },
                })
              : null;

            const termsMonths = (product as any)?.termsMonths || 12;

            // Calculate new dates
            const oldEndDate = new Date((policy as any).endDate);
            const newStartDate = new Date(oldEndDate);
            const newEndDate = new Date(oldEndDate);
            newEndDate.setMonth(newEndDate.getMonth() + termsMonths);

            // Generate premium schedules
            const premiumAmount = parseFloat((policy as any).premium?.toString() || '0');
            const freq = (policy as any).paymentFrequency || 'annual';
            const schedules = generatePremiumSchedules(
              'placeholder',
              tenantId,
              premiumAmount,
              freq,
              newStartDate,
              newEndDate
            );

            // Generate a new policy number
            const existingPoliciesCount = await db.policy.count({
              where: { tenantId, isDeleted: false },
            });
            const newPolicyNumber = `RNW-${String(existingPoliciesCount + 1).padStart(6, '0')}`;

            // Create the new renewed policy
            const renewedPolicy = await db.policy.create({
              data: {
                tenantId,
                policyNumber: newPolicyNumber,
                insuredId: (policy as any).insuredId || null,
                productId: (policy as any).productId || null,
                agentId: (policy as any).agentId || null,
                type: (policy as any).type || 'property',
                subType: (policy as any).subType || null,
                premium: (policy as any).premium || 0,
                coverage: (policy as any).coverage || 0,
                excessAmount: (policy as any).excessAmount || 0,
                deductibleAmount: (policy as any).deductibleAmount || 0,
                paymentFrequency: freq,
                startDate: newStartDate,
                endDate: newEndDate,
                sumInsured: (policy as any).sumInsured || 0,
                renewalCount: ((policy as any).renewalCount || 0) + 1,
                parentPolicyId: policy.id,
                status: 'active',
                beneficiaries: (policy as any).beneficiaries || '[]',
                notes: sanitizedNotes
                  ? `Renewal of policy ${policy.policyNumber || policy.id}. ${sanitizedNotes}`
                  : `Renewal of policy ${policy.policyNumber || policy.id}`,
                coInsurance: (policy as any).coInsurance || 0,
              },
            });

            // Create premium schedules for the new policy
            for (const schedule of schedules) {
              await db.premiumSchedule.create({
                data: {
                  tenantId,
                  policyId: renewedPolicy.id,
                  dueDate: schedule.dueDate,
                  amount: schedule.amount,
                  status: 'pending',
                },
              });
            }

            // Update old policy status to 'expired'
            await db.policy.update({
              where: { id: policy.id, tenantId },
              data: { status: 'expired' },
            });

            // Update renewal task
            await db.renewalTask.update({
              where: { id: taskId, tenantId },
              data: {
                status: 'renewed',
                completedDate: new Date(),
                notes: sanitizedNotes
                  ? `${(task as any).notes || ''}\n[${new Date().toISOString()}] RENEWED → ${newPolicyNumber}. ${sanitizedNotes}`
                  : `${(task as any).notes || ''}\n[${new Date().toISOString()}] RENEWED → ${newPolicyNumber}`,
              },
            });

            // Audit: renewal task status change
            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'renewal_task',
              entityId: taskId,
              changes: { status: { old: (task as any).status, new: 'renewed' } },
              metadata: {
                policyId: policy.id,
                policyNumber: policy.policyNumber,
                renewedPolicyId: renewedPolicy.id,
                renewedPolicyNumber: newPolicyNumber,
              },
            });

            // Audit: old policy status change
            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'status_change',
              entityType: 'policy',
              entityId: policy.id,
              changes: { status: { old: policy.status, new: 'expired' } },
              metadata: { policyNumber: policy.policyNumber, reason: 'renewed', renewedTo: newPolicyNumber },
            });

            // Audit: new policy creation
            auditLogger.log({
              tenantId,
              userId: auth.payload?.userId || auth.payload?.email || 'system',
              action: 'create',
              entityType: 'policy',
              entityId: renewedPolicy.id,
              metadata: {
                policyNumber: newPolicyNumber,
                parentPolicyId: policy.id,
                parentPolicyNumber: policy.policyNumber,
                renewalCount: ((policy as any).renewalCount || 0) + 1,
                premium: premiumAmount,
                premiumSchedulesCreated: schedules.length,
              },
            });

            processed.push({
              taskId,
              action: 'renew',
              status: 'renewed',
              oldPolicyId: policy.id,
              newPolicyId: renewedPolicy.id,
              newPolicyNumber,
              premiumSchedulesCreated: schedules.length,
            });
          }
        } catch (err: any) {
          errors.push({ taskId, error: err.message });
        }
      }

      return NextResponse.json({
        processedCount: processed.length,
        errorCount: errors.length,
        processed,
        errors,
      });
    }

    // ── POST ?action=generate-notices ──
    // Generates renewal notice data for policies expiring within a given period
    if (action === 'generate-notices') {
      const body = await req.json();
      const { daysAhead } = body as { daysAhead?: number };
      const days = typeof daysAhead === 'number' && daysAhead > 0 ? Math.min(daysAhead, 365) : 30;

      const now = new Date();
      const windowEnd = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

      // Fetch expiring policies with insured contact info
      const expiringPolicies = await db.policy.findMany({
        where: {
          tenantId,
          isDeleted: false,
          status: 'active',
          endDate: {
            gt: now,
            lte: windowEnd,
          },
        },
        include: {
          insured: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              email: true,
              phone: true,
              // nationalId and dateOfBirth intentionally excluded (PII)
            },
          },
          agent: {
            select: {
              id: true,
              firstName: true,
              lastName: true,
              email: true,
              phone: true,
            },
          },
          product: {
            select: {
              id: true,
              name: true,
              category: true,
            },
          },
        },
        orderBy: { endDate: 'asc' },
      });

      // Build notice records (PII-masked)
      const notices = expiringPolicies.map((p: any) => {
        const insured = (p as any).insured;
        const agent = (p as any).agent;
        const product = (p as any).product;

        const daysUntilExpiry = Math.max(
          0,
          Math.round(
            (new Date((p as any).endDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
          )
        );

        return {
          policyId: p.id,
          policyNumber: p.policyNumber,
          policyType: (p as any).type,
          policySubType: (p as any).subType,
          premium: p.premium,
          coverage: p.coverage,
          startDate: p.startDate,
          endDate: p.endDate,
          daysUntilExpiry,
          paymentFrequency: (p as any).paymentFrequency,
          renewalCount: (p as any).renewalCount || 0,
          insured: insured
            ? {
                id: insured.id,
                name: [insured.firstName, insured.lastName].filter(Boolean).join(' ') || '—',
                email: insured.email || null,
                phone: insured.phone || null,
                // nationalId and dateOfBirth NOT included (PII)
              }
            : null,
          agent: agent
            ? {
                id: agent.id,
                name: [agent.firstName, agent.lastName].filter(Boolean).join(' ') || '—',
                email: agent.email || null,
                phone: agent.phone || null,
              }
            : null,
          product: product
            ? {
                id: product.id,
                name: product.name,
                category: product.category,
              }
            : null,
        };
      });

      return NextResponse.json({
        generatedAt: new Date().toISOString(),
        daysAhead: days,
        totalNotices: notices.length,
        notices,
      });
    }

    return NextResponse.json(
      { error: 'Invalid action. Use process or generate-notices.' },
      { status: 400 }
    );
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
