import { NextRequest, NextResponse } from 'next/server';
import { pgQuery, pgQueryOne } from '@/lib/pg-query';

// ── WiPay Webhook Endpoint ──
// Receives POST notifications from WiPay when a payment status changes.
// This is a global endpoint (not tenant-scoped) — tenant is resolved from
// the transaction record via rentPaymentId.
//
// Flow:
//   1. Verify webhook signature using WiPay API key
//   2. Look up the WiPayTransaction record
//   3. Update transaction status
//   4. Update RentPayment status (mark as paid)
//   5. Send notification to landlord
//   6. Send receipt email to renter

// Ensure WiPayTransaction table exists (idempotent)
async function ensureWiPayTable() {
  await pgQuery(`
    CREATE TABLE IF NOT EXISTS "WiPayTransaction" (
      id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
      "tenantId"      TEXT NOT NULL,
      "rentPaymentId" TEXT,
      "renterId"      TEXT,
      "paymentMethod" TEXT NOT NULL DEFAULT 'wipay',
      status          TEXT NOT NULL DEFAULT 'initiated',
      amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
      currency        TEXT NOT NULL DEFAULT 'TTD',
      "processingFee" NUMERIC(14,2) NOT NULL DEFAULT 0,
      "wipayOrderId"      TEXT,
      "wipayTransactionId" TEXT,
      "wipayFee"          NUMERIC(14,2) NOT NULL DEFAULT 0,
      "wipayCurrency"     TEXT,
      "cardType"          TEXT,
      "cardLast4"         TEXT,
      "customerName"  TEXT,
      "customerEmail" TEXT,
      "customerPhone" TEXT,
      "cashReference" TEXT,
      "cashNotes"     TEXT,
      "refundAmount"    NUMERIC(14,2) NOT NULL DEFAULT 0,
      "refundReason"    TEXT,
      "refundedAt"      TIMESTAMPTZ,
      "ipAddress"       TEXT,
      "initiatedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "completedAt"   TIMESTAMPTZ,
      "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pgQuery(`CREATE INDEX IF NOT EXISTS "idx_WiPayTransaction_tenantId" ON "WiPayTransaction"("tenantId")`);
  await pgQuery(`CREATE INDEX IF NOT EXISTS "idx_WiPayTransaction_rentPaymentId" ON "WiPayTransaction"("rentPaymentId")`);
  await pgQuery(`CREATE INDEX IF NOT EXISTS "idx_WiPayTransaction_wipayTransactionId" ON "WiPayTransaction"("wipayTransactionId")`);
  await pgQuery(`CREATE INDEX IF NOT EXISTS "idx_WiPayTransaction_tenant_status" ON "WiPayTransaction"("tenantId", status)`);
}

/**
 * Send a notification to the landlord about a payment event.
 */
async function notifyLandlord(tenantId: string, title: string, message: string, metadata: any) {
  try {
    const { db } = await import('@/lib/db');
    await db.notification.create({
      data: {
        tenantId,
        title,
        message,
        type: 'payment_received',
        category: 'payment',
        metadata: JSON.stringify(metadata),
      },
    });
  } catch (error) {
    console.error('[WiPay Webhook] Failed to create landlord notification:', error);
  }
}

/**
 * Send a receipt email to the renter.
 */
async function sendReceiptEmail(email: string, data: any) {
  try {
    const { sendEmail } = await import('@/lib/email');
    await sendEmail(
      email,
      `Payment Receipt - ${data.description || 'Rent Payment'}`,
      `
        <div style="max-width: 600px; margin: 0 auto; font-family: sans-serif;">
          <h2 style="color: #1D4ED8;">Payment Confirmation</h2>
          <p>Thank you for your payment!</p>
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr><td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold;">Description</td><td style="padding: 8px; border: 1px solid #e5e7eb;">${data.description || 'Rent Payment'}</td></tr>
            <tr><td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold;">Amount</td><td style="padding: 8px; border: 1px solid #e5e7eb;">${data.currency || 'TTD'} ${data.amount}</td></tr>
            <tr><td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold;">Transaction ID</td><td style="padding: 8px; border: 1px solid #e5e7eb;">${data.transactionId || 'N/A'}</td></tr>
            <tr><td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold;">Date</td><td style="padding: 8px; border: 1px solid #e5e7eb;">${new Date().toLocaleDateString()}</td></tr>
            <tr><td style="padding: 8px; border: 1px solid #e5e7eb; font-weight: bold;">Method</td><td style="padding: 8px; border: 1px solid #e5e7eb;">${data.cardType ? data.cardType.toUpperCase() + ' ****' + (data.cardLast4 || '') : 'WiPay Online'}</td></tr>
          </table>
          <p style="color: #6b7280; font-size: 14px;">This receipt was automatically generated by Zeitgeist Business Solutions.</p>
        </div>
      `
    );
  } catch (error) {
    console.error('[WiPay Webhook] Failed to send receipt email:', error);
  }
}

// ── POST: Receive webhook from WiPay when payment completes ──
export async function POST(req: NextRequest) {
  try {
    await ensureWiPayTable();

    const body = await req.json();

    // Validate required fields
    const transactionId = body.transaction_id || body.transactionId;
    const status = body.status;
    const signature = body.signature;

    if (!transactionId || !status) {
      return NextResponse.json(
        { error: 'Missing required fields: transaction_id and status' },
        { status: 400 }
      );
    }

    // Verify webhook signature
    const { getWiPay } = await import('@/lib/wipay');
    const wipay = getWiPay();

    if (wipay.isConfigured() && signature) {
      const isValid = wipay.verifySignature(transactionId, signature);
      if (!isValid) {
        console.warn(`[WiPay Webhook] Invalid signature for transaction ${transactionId}`);
        // Still return 200 to acknowledge but log the issue
        // We don't reject because some WiPay integrations don't support signatures
      }
    }

    // Look up the existing WiPayTransaction by WiPay transaction ID
    let txn = await pgQueryOne(
      `SELECT * FROM "WiPayTransaction" WHERE "wipayTransactionId" = $1`,
      [transactionId]
    );

    // If not found by WiPay transaction ID, try by order ID
    const orderId = body.order_id || body.orderId;
    if (!txn && orderId) {
      txn = await pgQueryOne(
        `SELECT * FROM "WiPayTransaction" WHERE "wipayOrderId" = $1 AND "paymentMethod" = 'wipay'`,
        [orderId]
      );
    }

    if (!txn) {
      console.warn(`[WiPay Webhook] No matching transaction found for WiPay TX ${transactionId}`);
      return NextResponse.json({
        success: true,
        note: 'Transaction not found in system — possibly already processed or not originated from this platform.',
      });
    }

    // Prevent re-processing already completed transactions
    if (txn.status === 'completed' && status === 'completed') {
      return NextResponse.json({ success: true, note: 'Transaction already processed.' });
    }

    // Determine new status
    let newStatus: string;
    switch (status.toLowerCase()) {
      case 'success':
      case 'completed':
      case 'approved':
        newStatus = 'completed';
        break;
      case 'failed':
      case 'declined':
      case 'rejected':
        newStatus = 'failed';
        break;
      case 'refunded':
      case 'reversed':
        newStatus = 'refunded';
        break;
      case 'expired':
      case 'cancelled':
      case 'timeout':
        newStatus = 'expired';
        break;
      case 'pending':
      case 'processing':
        newStatus = 'processing';
        break;
      default:
        newStatus = 'processing';
    }

    // Update the WiPayTransaction record
    const now = new Date().toISOString();
    await pgQuery(
      `UPDATE "WiPayTransaction"
       SET "wipayTransactionId" = COALESCE("wipayTransactionId", $1),
           "wipayFee" = $2,
           "wipayCurrency" = $3,
           "cardType" = $4,
           "cardLast4" = $5,
           "customerName" = COALESCE(NULLIF($6, ''), "customerName"),
           "customerEmail" = COALESCE(NULLIF($7, ''), "customerEmail"),
           status = $8,
           "completedAt" = CASE WHEN $8 = 'completed' THEN $9 ELSE "completedAt" END,
           "updatedAt" = $9
       WHERE id = $10`,
      [
        transactionId,
        parseFloat(body.fee || body.wipayFee || '0'),
        body.currency || body.wipayCurrency || txn.currency,
        body.card_type || body.cardType || null,
        body.card_last4 || body.cardLast4 || null,
        body.name || body.customer_name || body.customerName || null,
        body.email || body.customer_email || body.customerEmail || null,
        newStatus,
        newStatus === 'completed' ? now : null,
        txn.id,
      ]
    );

    // If payment completed, update RentPayment and send notifications
    if (newStatus === 'completed') {
      try {
        const { db } = await import('@/lib/db');

        // Find and update the rent payment
        if (txn.rentPaymentId) {
          const rentPayment = await db.rentPayment.findUnique({
            where: { id: txn.rentPaymentId },
            include: { property: true, lease: true, unit: true },
          });

          if (rentPayment) {
            const totalPaid = Number(rentPayment.amountPaid) + Number(txn.amount);
            const amountDue = Number(rentPayment.amountDue) + Number(rentPayment.lateFee);

            const paymentStatus = totalPaid >= amountDue ? 'paid' : 'partial';

            await db.rentPayment.update({
              where: { id: txn.rentPaymentId },
              data: {
                status: paymentStatus,
                amountPaid: totalPaid,
                paymentMethod: 'wipay',
                paymentRef: transactionId,
                paidAt: paymentStatus === 'paid' ? new Date() : rentPayment.paidAt,
              },
            });

            // Send notification to landlord
            await notifyLandlord(
              txn.tenantId,
              `Payment Received - ${rentPayment.property?.name || 'Property'}`,
              `A payment of ${txn.currency} ${Number(txn.amount).toFixed(2)} has been received via WiPay for unit ${rentPayment.unit?.unitNumber || 'N/A'}. Transaction ID: ${transactionId}`,
              {
                type: 'wipay_payment_completed',
                rentPaymentId: txn.rentPaymentId,
                transactionId,
                amount: Number(txn.amount),
                currency: txn.currency,
                propertyId: rentPayment.propertyId,
                unitId: rentPayment.unitId,
              }
            );

            // Send receipt email to renter
            if (txn.customerEmail || txn.renterId) {
              let renterEmail = txn.customerEmail;
              if (!renterEmail && txn.renterId) {
                const renter = await db.renter.findUnique({ where: { id: txn.renterId } });
                renterEmail = renter?.email;
              }
              if (renterEmail) {
                await sendReceiptEmail(renterEmail, {
                  description: `Rent - ${rentPayment.property?.name || 'Property'} Unit ${rentPayment.unit?.unitNumber || ''}`,
                  amount: Number(txn.amount).toFixed(2),
                  currency: txn.currency,
                  transactionId,
                  cardType: body.card_type || body.cardType,
                  cardLast4: body.card_last4 || body.cardLast4,
                });
              }
            }
          }
        }
      } catch (innerError) {
        console.error('[WiPay Webhook] Error updating RentPayment:', innerError);
        // Don't return error — the transaction record is already updated
        // The rent payment can be manually reconciled
      }
    }

    // Handle refund status
    if (newStatus === 'refunded') {
      try {
        const { db } = await import('@/lib/db');
        if (txn.rentPaymentId) {
          const rentPayment = await db.rentPayment.findUnique({
            where: { id: txn.rentPaymentId },
          });
          if (rentPayment) {
            const newPaid = Math.max(0, Number(rentPayment.amountPaid) - Number(txn.amount));
            const newStatus = newPaid <= 0 ? 'pending' : 'partial';
            await db.rentPayment.update({
              where: { id: txn.rentPaymentId },
              data: {
                amountPaid: newPaid,
                status: newStatus,
                paymentRef: null,
                paidAt: newStatus === 'pending' ? null : rentPayment.paidAt,
              },
            });
          }
        }

        // Notify landlord about refund
        await notifyLandlord(
          txn.tenantId,
          'Payment Refunded',
          `A refund of ${txn.currency} ${Number(txn.amount).toFixed(2)} has been processed for transaction ${transactionId}.`,
          { type: 'wipay_payment_refunded', transactionId, amount: Number(txn.amount) }
        );
      } catch (innerError) {
        console.error('[WiPay Webhook] Error processing refund:', innerError);
      }
    }

    return NextResponse.json({
      success: true,
      transactionId,
      status: newStatus,
    });
  } catch (error: any) {
    console.error('[WiPay Webhook] Error processing webhook:', error);
    // Return 200 to prevent WiPay from retrying excessively
    return NextResponse.json(
      { error: error.message, note: 'Webhook received but processing failed' },
      { status: 200 }
    );
  }
}

// ── GET: Health check for the webhook endpoint ──
export async function GET() {
  return NextResponse.json({
    status: 'ok',
    service: 'wipay-webhook',
    timestamp: new Date().toISOString(),
  });
}
